# Use the official MySQL 8.0 image from Docker Hub
FROM mysql:latest

# Set the root password
ENV MYSQL_ROOT_PASSWORD=password

# Set the default database name
ENV MYSQL_DATABASE=mysql



# Expose port 3306 to connect to the MySQL server
EXPOSE 3306